pipeline {
 agent any
 stages {
 stage('Clone Repository') {
 steps {
 git url: 'pipeline {
 agent any
 stages {
 stage('Clone Repository') {
 steps {
 git url: 'https://github.com/Nimbra12/fa21-bse-020-TOCS-.git'
 }
 }
 stage('Build Website') {
 steps {
 sh './hello.sh'
 }
 }
 stage('HTML Validation') {
 steps {
 echo 'Running HTML Validation...'
 sh 'tidy -q -e index.html || echo "HTML issues detected!"'
 }
 }
 stage('Build Website') {
 steps {
 sh './hello.sh'
 }
 }
 stage('HTML Validation') {
 steps {
 echo 'Running HTML Validation...'
 sh 'tidy -q -e index.html || echo "HTML issues detected!"